apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-api
spec:
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
      - name: spring-api
        image: shboland/spring-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "265Mi"
            cpu: "400m"
