apiVersion: v1
kind: Service
metadata:
  name: spring-api
spec:
  template:
    metadata:
      labels:
        app: spring-api
  type: NodePort
  ports:
  - nodePort: 31311
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-api