apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-api
spec:
  template:
    spec:
      containers:
      - name: spring-api
        image: shboland/spring-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 6
